### ISSUE TITLE
اضافه کردن لینک ویکی پدیا

### ISSUE THREAD

**Issue by vahid-sohrabloo** [persiancal/cal-events#1]
به نظرم لینک ویکی پدیا هم اضافه بشه به هر مناسبت بد نباشه

**Comment by fzerorubigd** [comment]
اضافه کردن لینک یکی از اهداف اصلی من بوده برای این مخزن. منتها اینکار رو نکردم تا تصمیم گرفته بشه چطور باید لینکها رو اضافه کرد مثلا این 
```yaml
Links:
  - Fa_IR:
    ویکی :‌ http://wikipedia.org
  - En_US:
    wiki: http://wikipedia.org
```

یا 

```yaml
Links:
  ویکی: http://wikipedia.org
  wiki: http://wikipedia.org
```

در مورد اولی سوال اینه تقسیم بندی به زبان بر چه مبنایی باید باشه؟ برمبنای زبان خود ویکی؟ یعنی لینک انگلیسی بره به ویکی انکلیسی و لینک فارسی بره به ویکی فارسی؟ یا اینکه همه لینکها باشن، با یه عنوان ترجمه شده مثل این 

```yaml
Links:
  - http://link1
  - http://link2
  Captions:
    -Fa_IR: 
      - لینک اول 
      - آخری
    -En_US:
      - first
      - last
```
