### ISSUE TITLE
ویرایش و مرتب سازی رویدادهای ماههای مختلف شمسی 

### ISSUE THREAD

**Issue by fzerorubigd** [persiancal/cal-events#11]
با توجه به اینکه تقریبا یک ساختار اولیه و نا کامل وجود داره، میشه اطلاعات رو اضافه کرد. پیشنهاد من اینه که ماه به ماه رو به یه نفر بسپاریم و درنهایت یه نفر دیگه بررسی کنه و در آخر هم اگه تغییری در ساختار دادیم اصلاحشون کنیم. 

برای هر ماه یک ایشو میسازیم و به شخص میسپاریم.

**Comment by okian** [comment]
من آمادگی دارم، هر ماهی رو خواستی اساین کن

**Comment by neda1985** [comment]
من هم امادگی دارم  به منم اساین کنید

**Comment by dariubs** [comment]
و من هم آمادگی دارم تعدادی رو انجام بدم

**Comment by fzerorubigd** [comment]
به ارگانیزیشن گیتهاب اضافتون کردم.

@neda1985 کار داوطلبانست، لطف میکنید، و اصلا مشکلی نداره. 
از طرفی هنوز یه فلوی مشخص یا یه ابزار برای ویرایش و دیدن یه روز نیست، پیشنهادی داشتین بگین و البته یه وب سرور کوچیک تو ذهنم هست بنویسم برای ویرایش ولی خب یکم طول میکشه

**Comment by okian** [comment]
موافقید ساختار پوشه‌ها رو اینطور در نظر بگیریم که پوشه تقویم داشته باشیم و برای هم تقویم یک پوشه و داخلش فایلها‌رو؟
 اینطور هم کمتر کانفلیکت به وجود میاد و فایل‌ها کوچکتر مشین و کار باهاشون راحت‌تر. 
مثلا:
```
calendar
├── hijri
│  ├── 1.yaml
│  ├── 2.yaml
│  ├── 3.yaml
│  ├── 4.yaml
│  ├── 5.yaml
│  ├── 6.yaml
│  ├── 7.yaml
│  ├── 8.yaml
│  ├── 9.yaml
│  ├── 10.yaml
│  ├── 11.yaml
│  └── 12.yaml
└── jalali
   ├── 1.yaml
   ├── 2.yaml
   ├── 3.yaml
   ├── 4.yaml
   ├── 5.yaml
   ├── 6.yaml
   ├── 7.yaml
   ├── 8.yaml
   ├── 9.yaml
   ├── 10.yaml
   ├── 11.yaml
   └── 12.yaml
```
مورد دیگه اینکه رویدادها به ترتیب اتفاق در هر فایل ثبت شوند و به ته فایل اپند نشوند. اینطور جلوی ثبت تکراری گرفته میشه.

**Comment by neda1985** [comment]
من خیلی موافقم

**Comment by fzerorubigd** [comment]
مدیریت تعداد زیادی فایل از یه لحاظ ساده‌تره، چون کانفلیکت کمتری داریم.
و البته اینکه چون نهایتا همه چی منتقل میشه به پوشه دیست، و اونجا همین
ساختار تک فایلی رو نگه میداریم.
منتها تفکیک تو روز رو موافق نیستم. به نظر تفکیک ماهیانه کافیه، اگه زیاد شد
بعدا میشه تفکیک روزانه کرد، فقط میشه لطفا به ایشوی دیگه درست کنی؟

**Comment by okian** [comment]
@fzerorubigd شاید شفاف نگفتم٬ اون اعداد شماره ماه هست به جای اسم ماه نه شماره روز از سال

**Comment by hramezani** [comment]
@fzerorubigd منم میتونم کمک کنم.

**Comment by fzerorubigd** [comment]
@hramezani یکی از ماههای اساین نشده رو انتخاب کن و شروع کن

**Comment by fzerorubigd** [comment]
برای اینکار لطفا این ایشو رو بخونید 

https://github.com/persiancal/cal-events/issues/9

**Comment by fzerorubigd** [comment]
الان برای یک کلید کامل این استراکچر لازمه :‌

```yaml
- partial_key: "newrouz"     # this is the partial key, for a single event with multiple day, use one partial key (like newrouz for all days of newrouz.) 
  title:
    fa_IR: آغاز عید نوروز
  description:
    fa_IR: آغاز عید نوروز
  month: 1
  day: 1
  calendar:
    en_US:
    - Iran
    fa_IR:
    - ایران
  holiday:
    Iran: []
  sources:
    - https://fa.wikipedia.org/wiki/نوروز
```

فعلا برای تعطیلات چند روزه چیزی اضافه نشده، ولی اگر با چنین تعطیلاتی روبرو شدید لطفا یک کلید 
`TODO`
اضافه کنید
