### ISSUE TITLE
روزهای تعطیل

### ISSUE THREAD

**Issue by tavallaie** [persiancal/cal-events#163]
برای روزهای تعطیل در هر کدوم از تقویم ها در هر موقعیت جغرافیایی چه کار کنیم؟ 
یعنی تعطیل بودن یا نبودن مهمه؟ اگه هست منطقه جغرافیاییش چی؟

**Comment by okian** [comment]
باید از کلید 
```yaml
  holiday:
    Iran: []
    Iraq: []
```
استفاده کنید
فعلا فقط ایران کافی هست. در صورت نیاز بعدا باقی مناطق رو اضافه میکنیم
