### ISSUE TITLE
Change the month structure

### ISSUE THREAD

**Issue by fzerorubigd** [persiancal/cal-events#169]
ساختار ماه در فایل 
`preset.yaml`
الان به صورت ستونی دیده شده، بهتره که ساختار این شکلی بشه : 
```yaml
months: 
 - name: 
   en_US: Esfand
   fa_IR: اسفند
 leap: 29 
 normal: 30
```
