### ISSUE TITLE
ماه ربیع‌الثانی، تقویم هجری قمری

### ISSUE THREAD

**Issue by fzerorubigd** [persiancal/cal-events#69]
[مستندات](https://github.com/persiancal/cal-events/blob/master/docs/events.md) مربوط به کلیدهای رویداد را ببینید

و اگر سوالی داشتید هم برای اینکه یکجا باشد در ایشوی شماره #65 بپرسید

**Comment by irajtaghlidi** [comment]
اینم برای من.

**Comment by irajtaghlidi** [comment]
در فایل های قمری کلید calendar رو باید چی بزنیم؟

الگو زیر درست ؟

```
events:
- partial_key: "tawwabin_uprising"
  title:
    fa_IR: قیام توابین
  description:
    fa_IR: وقوع قیام توابین توسط گروهی از شیعیان کوفه به خونخواهی کشتگان نبرد کربلا به رهبری سلیمان بن صرد خزاعی
  month: 1
  day: 1
  calendar:
    en_US:
    - Iran
    fa_IR:
    - ایران
  holiday:
    Iran: []
  sources:
    - https://fa.wikipedia.org/wiki/نهضت_توابین
```
